package quic

//go:generate sh -c "./mockgen_private.sh quic mock_send_conn_test.go github.com/fkwhite/Superquic-v1 sendConn"
//go:generate sh -c "./mockgen_private.sh quic mock_sender_test.go github.com/fkwhite/Superquic-v1 sender"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_internal_test.go github.com/fkwhite/Superquic-v1 streamI"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_stream_test.go github.com/fkwhite/Superquic-v1 cryptoStream"
//go:generate sh -c "./mockgen_private.sh quic mock_receive_stream_internal_test.go github.com/fkwhite/Superquic-v1 receiveStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_send_stream_internal_test.go github.com/fkwhite/Superquic-v1 sendStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_sender_test.go github.com/fkwhite/Superquic-v1 streamSender"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_getter_test.go github.com/fkwhite/Superquic-v1 streamGetter"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_data_handler_test.go github.com/fkwhite/Superquic-v1 cryptoDataHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_frame_source_test.go github.com/fkwhite/Superquic-v1 frameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_ack_frame_source_test.go github.com/fkwhite/Superquic-v1 ackFrameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_manager_test.go github.com/fkwhite/Superquic-v1 streamManager"
//go:generate sh -c "./mockgen_private.sh quic mock_sealing_manager_test.go github.com/fkwhite/Superquic-v1 sealingManager"
//go:generate sh -c "./mockgen_private.sh quic mock_unpacker_test.go github.com/fkwhite/Superquic-v1 unpacker"
//go:generate sh -c "./mockgen_private.sh quic mock_packer_test.go github.com/fkwhite/Superquic-v1 packer"
//go:generate sh -c "./mockgen_private.sh quic mock_mtu_discoverer_test.go github.com/fkwhite/Superquic-v1 mtuDiscoverer"
//go:generate sh -c "./mockgen_private.sh quic mock_session_runner_test.go github.com/fkwhite/Superquic-v1 sessionRunner"
//go:generate sh -c "./mockgen_private.sh quic mock_quic_session_test.go github.com/fkwhite/Superquic-v1 quicSession"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_test.go github.com/fkwhite/Superquic-v1 packetHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_unknown_packet_handler_test.go github.com/fkwhite/Superquic-v1 unknownPacketHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_manager_test.go github.com/fkwhite/Superquic-v1 packetHandlerManager"
//go:generate sh -c "./mockgen_private.sh quic mock_multiplexer_test.go github.com/fkwhite/Superquic-v1 multiplexer"
//go:generate sh -c "./mockgen_private.sh quic mock_batch_conn_test.go github.com/fkwhite/Superquic-v1 batchConn"
//go:generate sh -c "mockgen -package quic -self_package github.com/fkwhite/Superquic-v1 -destination mock_token_store_test.go github.com/fkwhite/Superquic-v1 TokenStore"
//go:generate sh -c "mockgen -package quic -self_package github.com/fkwhite/Superquic-v1 -destination mock_packetconn_test.go net PacketConn"
